// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketlog.Data;

namespace Ticketlog.Migrations
{
    [DbContext(typeof(EstadoContext))]
    [Migration("20210219023212_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ticketlog.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CustoCidadeUS")
                        .HasColumnType("float");

                    b.Property<int?>("IdEstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Populacao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdEstadoId");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Ticketlog.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CustoEstadoUS")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Populacao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Ticketlog.Models.ParametroCusto", b =>
                {
                    b.Property<double>("Descontos")
                        .HasColumnType("float");

                    b.Property<double>("PorPessoa")
                        .HasColumnType("float");

                    b.Property<double>("ValorCorte")
                        .HasColumnType("float");

                    b.ToTable("ParametroCustos");
                });

            modelBuilder.Entity("Ticketlog.Models.Cidade", b =>
                {
                    b.HasOne("Ticketlog.Models.Estado", "IdEstado")
                        .WithMany()
                        .HasForeignKey("IdEstadoId");

                    b.Navigation("IdEstado");
                });
#pragma warning restore 612, 618
        }
    }
}
